import { FormEvent, useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertCircle, CheckCircle2, History, RotateCcw, Save, Settings, ShieldCheck, SlidersHorizontal, X } from 'lucide-react';
import { settingService, SystemSettings, TariffPlan } from '../services/settingService';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';
import { usePermission } from '../hooks/usePermission';

const EMPTY: SystemSettings = { businessName: '', branchName: '', address: '', gstin: '', invoicePrefix: 'INV', receiptPrefix: 'RCP', renewalReminderDays: 30, offlineCacheHours: 24 };
const money = (value: number) => `₹${value.toLocaleString('en-IN')}`;
const dateLabel = (value: string) => new Date(value).getTime() === 0 ? 'Initial baseline' : new Date(value).toLocaleDateString('en-IN');

export function SettingsPage() {
  const canManage = usePermission('settings.manage');
  const queryClient = useQueryClient();
  const settingsQuery = useQuery({ queryKey: ['system-settings'], queryFn: settingService.get });
  const [form, setForm] = useState<SystemSettings>(EMPTY);
  const [editing, setEditing] = useState<TariffPlan | null>(null);
  const [historySize, setHistorySize] = useState<string | null>(null);
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const historyQuery = useQuery({ queryKey: ['tariff-history', historySize], queryFn: () => settingService.history(historySize!), enabled: Boolean(historySize) });
  const data = settingsQuery.data;
  const tariffs = data?.tariffs || [];
  const isDirty = Boolean(data?.settings && JSON.stringify(form) !== JSON.stringify(data.settings));
  const averages = useMemo(() => ({ rent: tariffs.length ? Math.round(tariffs.reduce((n, t) => n + t.annualRent, 0) / tariffs.length) : 0, deposit: tariffs.length ? Math.round(tariffs.reduce((n, t) => n + t.securityDeposit, 0) / tariffs.length) : 0 }), [tariffs]);

  useEffect(() => { if (data?.settings) setForm(data.settings); }, [data]);
  useEffect(() => { const guard = (event: BeforeUnloadEvent) => { if (isDirty) event.preventDefault(); }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [isDirty]);
  const save = useMutation({ mutationFn: settingService.update, onSuccess: () => { setError(''); setMessage('Settings saved successfully.'); queryClient.invalidateQueries({ queryKey: ['system-settings'] }); }, onError: (err: any) => setError(err.response?.data?.message || err.message || 'Settings could not be saved.') });
  const revise = useMutation({ mutationFn: settingService.revise, onSuccess: () => { setEditing(null); setMessage('New tariff version activated. Existing agreements remain unchanged.'); queryClient.invalidateQueries({ queryKey: ['system-settings'] }); }, onError: (err: any) => setError(err.response?.data?.message || err.message || 'Tariff revision could not be activated.') });
  const field = (key: keyof SystemSettings, value: string) => setForm((old) => ({ ...old, [key]: typeof old[key] === 'number' ? Number(value) : value }));
  const discard = () => { if (data?.settings) setForm(data.settings); setError(''); setMessage(''); };
  const submitSettings = (event: FormEvent) => { event.preventDefault(); setMessage(''); setError(''); if (!form.businessName.trim()) return setError('Business name is required.'); if (!/^[A-Z0-9-]{2,12}$/.test(form.invoicePrefix) || !/^[A-Z0-9-]{2,12}$/.test(form.receiptPrefix)) return setError('Invoice and receipt prefixes must be 2–12 uppercase letters, numbers or hyphens.'); if (form.gstin && !/^\d{2}[A-Z]{5}\d{4}[A-Z][A-Z\d]Z[A-Z\d]$/.test(form.gstin)) return setError('Enter a valid 15-character GSTIN or leave it blank.'); save.mutate(form); };
  const submitTariff = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const fd = new FormData(event.currentTarget); revise.mutate({ size: editing.size, annualRent: Number(fd.get('annualRent')), securityDeposit: Number(fd.get('securityDeposit')), effectiveFrom: String(fd.get('effectiveFrom')), notes: String(fd.get('notes') || '') }); };
  const textField = (key: keyof SystemSettings, label: string, help?: string) => <label className="text-xs font-bold text-slate-700">{label}<Input value={String(form[key])} onChange={(e) => field(key, ['gstin','invoicePrefix','receiptPrefix'].includes(key) ? e.target.value.toUpperCase() : e.target.value)} maxLength={key === 'gstin' ? 15 : key.toLowerCase().includes('prefix') ? 12 : undefined} className="mt-1.5" />{help && <span className="mt-1 block text-[10px] font-normal text-slate-500">{help}</span>}</label>;

  return <div className="space-y-5">
    <section className="flex flex-col gap-4 rounded-xl border border-slate-200 bg-white p-5 shadow-sm sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-blue-700"><Settings className="h-6 w-6" /></div><div><h1 className="text-xl font-bold text-slate-900">System Settings & Tariff Master</h1><p className="text-sm text-slate-500">Business identity, numbering policies and versioned locker tariffs</p></div></div><span className="inline-flex w-fit items-center gap-2 rounded-full border border-emerald-200 bg-emerald-50 px-3 py-1.5 text-xs font-semibold text-emerald-800"><ShieldCheck className="h-4 w-4" />Configuration audit enabled</span></section>
    {message && <div role="status" className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm font-medium text-emerald-800"><CheckCircle2 className="h-4 w-4" />{message}</div>}
    {(settingsQuery.isError || error) && <div role="alert" className="flex items-center gap-2 rounded-lg border border-rose-200 bg-rose-50 p-3 text-sm text-rose-800"><AlertCircle className="h-4 w-4" />{error || (settingsQuery.error instanceof Error ? settingsQuery.error.message : 'Settings could not be loaded.')}</div>}
    <form onSubmit={submitSettings} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-5 flex flex-col gap-3 border-b pb-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-bold">Business & System Configuration</h2><p className="mt-1 text-xs text-slate-500">Used on invoices, receipts, reminders and offline workstations.</p>{isDirty && <span className="mt-2 inline-flex items-center gap-1 rounded-md bg-amber-50 px-2 py-1 text-xs font-medium text-amber-700"><AlertCircle className="h-3.5 w-3.5" />Unsaved changes</span>}</div>{canManage && <div className="flex gap-2">{isDirty && <Button type="button" variant="outline" onClick={discard} className="gap-2"><RotateCcw className="h-4 w-4" />Discard</Button>}<Button disabled={save.isPending || settingsQuery.isLoading || !isDirty} className="gap-2"><Save className="h-4 w-4" />{save.isPending ? 'Saving…' : 'Save changes'}</Button></div>}</div>
      <fieldset disabled={!canManage} className="space-y-5"><legend className="sr-only">System configuration</legend>
        <section><h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">Business identity</h3><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{textField('businessName','Business Name','Printed on invoices and receipts.')}{textField('branchName','Branch Name')}{textField('gstin','GSTIN','Optional 15-character tax identifier.')}<label className="text-xs font-bold text-slate-700 sm:col-span-2 lg:col-span-3">Registered Address<Input value={form.address} onChange={(e) => field('address',e.target.value)} className="mt-1.5" /></label></div></section>
        <section className="border-t pt-5"><h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">Document numbering</h3><div className="grid gap-4 sm:grid-cols-2">{textField('invoicePrefix','Invoice Prefix','2–12 uppercase letters, numbers or hyphens.')}{textField('receiptPrefix','Receipt Prefix','2–12 uppercase letters, numbers or hyphens.')}</div><div className="mt-3 rounded-lg border border-blue-100 bg-blue-50/60 px-3 py-2 text-xs text-blue-900"><strong>Preview:</strong> <span className="font-mono">{form.invoicePrefix || 'INV'}-YYYY-######</span> · <span className="font-mono">{form.receiptPrefix || 'RCP'}-YYYY-######</span></div></section>
        <section className="border-t pt-5"><h3 className="mb-3 text-xs font-bold uppercase tracking-wider text-slate-500">Operational policies</h3><div className="grid gap-4 sm:grid-cols-2"><NumberField label="Renewal Reminder Days" value={form.renewalReminderDays} min={1} max={365} help="Advance notice before a renewal is due." onChange={(v) => field('renewalReminderDays',v)} /><NumberField label="Offline Cache Hours" value={form.offlineCacheHours} min={1} max={168} help="Maximum age of cached operational data." onChange={(v) => field('offlineCacheHours',v)} /></div></section>
      </fieldset>
    </form>
    <section aria-label="Tariff overview" className="grid gap-3 sm:grid-cols-3">{[['Active locker sizes', tariffs.length], ['Average annual rent', money(averages.rent)], ['Average deposit', money(averages.deposit)]].map(([label,value]) => <div key={String(label)} className="rounded-xl border bg-white p-4 shadow-sm"><p className="text-xs font-semibold text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold">{value}</p></div>)}</section>
    <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><header className="flex items-center gap-2 border-b p-4"><SlidersHorizontal className="h-5 w-5 text-blue-700"/><div><h2 className="font-bold">Active Tariff Matrix</h2><p className="text-xs text-slate-500">Versioned revisions never rewrite existing allocation snapshots.</p></div></header><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="sr-only">Current tariffs</caption><thead className="bg-slate-50 text-slate-600"><tr><th className="p-3 text-left">Size</th><th className="p-3 text-right">Annual Rent</th><th className="p-3 text-right">Deposit</th><th className="p-3 text-center">Version</th><th className="p-3 text-left">Effective</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{tariffs.map((t) => <tr key={t._id} className="border-t hover:bg-slate-50"><td className="p-3 font-bold"><span className="rounded-lg bg-slate-100 px-2.5 py-1.5">{t.size}</span></td><td className="p-3 text-right font-semibold">{money(t.annualRent)}</td><td className="p-3 text-right">{money(t.securityDeposit)}</td><td className="p-3 text-center"><span className="rounded-full bg-blue-50 px-2 py-1 text-xs font-semibold text-blue-700">v{t.version}</span></td><td className="p-3 text-slate-600">{dateLabel(t.effectiveFrom)}</td><td className="p-3"><div className="flex justify-end gap-2"><Button type="button" variant="ghost" size="sm" className="gap-1" onClick={() => setHistorySize(t.size)}><History className="h-3.5 w-3.5" />History</Button>{canManage && <Button type="button" variant="outline" size="sm" onClick={() => setEditing(t)}>Revise</Button>}</div></td></tr>)}</tbody></table></div></section>
    {editing && <RevisionDialog tariff={editing} pending={revise.isPending} close={() => setEditing(null)} submit={submitTariff} />}
    {historySize && <HistoryDialog size={historySize} rows={historyQuery.data || []} loading={historyQuery.isLoading} failed={historyQuery.isError} close={() => setHistorySize(null)} />}
  </div>;
}

function NumberField({ label,value,min,max,help,onChange }: { label:string; value:number; min:number; max:number; help:string; onChange:(value:string)=>void }) { return <label className="text-xs font-bold text-slate-700">{label}<Input type="number" min={min} max={max} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1.5" /><span className="mt-1 block text-[10px] font-normal text-slate-500">{help}</span></label>; }
function RevisionDialog({ tariff,pending,close,submit }: { tariff:TariffPlan; pending:boolean; close:()=>void; submit:(e:FormEvent<HTMLFormElement>)=>void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><form role="dialog" aria-modal="true" aria-labelledby="revision-title" onSubmit={submit} className="w-full max-w-md space-y-4 rounded-xl bg-white p-6 shadow-2xl"><DialogHead id="revision-title" title={`Revise Size ${tariff.size} Tariff`} subtitle={`Creates version ${tariff.version + 1}; historical rate is retained.`} close={close}/><div className="rounded-lg border border-blue-100 bg-blue-50 p-3 text-xs"><strong>Current:</strong> {money(tariff.annualRent)} rent · {money(tariff.securityDeposit)} deposit</div><NumberInput name="annualRent" label="Annual Rent" value={tariff.annualRent}/><NumberInput name="securityDeposit" label="Security Deposit" value={tariff.securityDeposit}/><label className="block text-xs font-bold">Effective From<Input name="effectiveFrom" type="date" min={new Date().toISOString().slice(0,10)} defaultValue={new Date().toISOString().slice(0,10)} className="mt-1" required /></label><label className="block text-xs font-bold">Revision reason / notes<Input name="notes" maxLength={500} className="mt-1" placeholder="Why is this tariff changing?" /></label><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={pending}>{pending ? 'Activating…' : 'Activate Revision'}</Button></div></form></div>; }
function NumberInput({ name,label,value }: { name:string; label:string; value:number }) { return <label className="block text-xs font-bold">{label}<Input name={name} type="number" min="0" step="0.01" defaultValue={value} className="mt-1" required /></label>; }
function DialogHead({ id,title,subtitle,close }: { id:string; title:string; subtitle:string; close:()=>void }) { return <div className="flex justify-between gap-3"><div><h2 id={id} className="text-lg font-bold">{title}</h2><p className="text-xs text-slate-500">{subtitle}</p></div><button type="button" onClick={close} className="grid h-10 w-10 place-items-center rounded-lg hover:bg-slate-100" aria-label="Close dialog"><X className="h-4 w-4" /></button></div>; }
function HistoryDialog({ size,rows,loading,failed,close }: { size:string; rows:TariffPlan[]; loading:boolean; failed:boolean; close:()=>void }) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><section role="dialog" aria-modal="true" aria-labelledby="history-title" className="w-full max-w-2xl overflow-hidden rounded-xl bg-white shadow-2xl"><header className="border-b p-5"><DialogHead id="history-title" title={`Size ${size} tariff history`} subtitle="Complete version trail for audit and comparison." close={close}/></header><div className="max-h-[60vh] overflow-auto p-5">{loading ? <p className="py-10 text-center text-sm text-slate-500">Loading revision history…</p> : failed ? <div role="alert" className="rounded-lg bg-rose-50 p-3 text-sm text-rose-800">Tariff history could not be loaded.</div> : <ol className="space-y-3">{rows.map((t,i) => <li key={t._id} className="flex gap-3 rounded-xl border p-4"><span className={`grid h-9 w-9 shrink-0 place-items-center rounded-full ${i === 0 ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100'}`}>{i === 0 ? <CheckCircle2 className="h-4 w-4"/> : <History className="h-4 w-4"/>}</span><div className="flex-1"><div className="flex flex-wrap justify-between gap-2"><strong>Version {t.version}{i === 0 && <small className="ml-2 rounded-full bg-emerald-50 px-2 py-0.5 text-emerald-700">Current</small>}</strong><span className="text-xs text-slate-500">{dateLabel(t.effectiveFrom)}</span></div><p className="mt-2 text-sm font-semibold">{money(t.annualRent)} rent · {money(t.securityDeposit)} deposit</p>{t.notes && <p className="mt-1 text-xs text-slate-500">{t.notes}</p>}</div></li>)}</ol>}</div></section></div>; }
