export const CLOSURE_TYPES = {
  NORMAL: 'NORMAL',
  CUSTOMER_REQUEST: 'CUSTOMER_REQUEST',
  NON_RENEWAL: 'NON_RENEWAL',
  TRANSFER: 'TRANSFER',
  ADMINISTRATIVE: 'ADMINISTRATIVE',
  LEGACY_IMPORT: 'LEGACY_IMPORT',
} as const;

export type ClosureType = typeof CLOSURE_TYPES[keyof typeof CLOSURE_TYPES];

export const CLOSURE_STATUSES = {
  DRAFT: 'DRAFT',
  PENDING_REVIEW: 'PENDING_REVIEW',
  PENDING_SETTLEMENT: 'PENDING_SETTLEMENT',
  READY_FOR_CLOSURE: 'READY_FOR_CLOSURE',
  APPROVED: 'APPROVED',
  COMPLETED: 'COMPLETED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
} as const;

export type ClosureStatus = typeof CLOSURE_STATUSES[keyof typeof CLOSURE_STATUSES];

export const OPEN_CLOSURE_STATUSES: ClosureStatus[] = [
  CLOSURE_STATUSES.DRAFT,
  CLOSURE_STATUSES.PENDING_REVIEW,
  CLOSURE_STATUSES.PENDING_SETTLEMENT,
  CLOSURE_STATUSES.READY_FOR_CLOSURE,
  CLOSURE_STATUSES.APPROVED,
];

export const LOCKER_CONDITIONS = {
  GOOD: 'GOOD',
  MINOR_DAMAGE: 'MINOR_DAMAGE',
  DAMAGED: 'DAMAGED',
  KEY_ISSUE: 'KEY_ISSUE',
  OTHER: 'OTHER',
} as const;

export type LockerCondition = typeof LOCKER_CONDITIONS[keyof typeof LOCKER_CONDITIONS];

// Centralized state transition map for Maker-Checker workflow
export const VALID_CLOSURE_TRANSITIONS: Record<ClosureStatus, ClosureStatus[]> = {
  [CLOSURE_STATUSES.DRAFT]: [
    CLOSURE_STATUSES.PENDING_REVIEW,
    CLOSURE_STATUSES.CANCELLED,
  ],
  [CLOSURE_STATUSES.PENDING_REVIEW]: [
    CLOSURE_STATUSES.PENDING_SETTLEMENT,
    CLOSURE_STATUSES.READY_FOR_CLOSURE,
    CLOSURE_STATUSES.REJECTED,
    CLOSURE_STATUSES.CANCELLED,
  ],
  [CLOSURE_STATUSES.PENDING_SETTLEMENT]: [
    CLOSURE_STATUSES.READY_FOR_CLOSURE,
    CLOSURE_STATUSES.REJECTED,
    CLOSURE_STATUSES.CANCELLED,
  ],
  [CLOSURE_STATUSES.READY_FOR_CLOSURE]: [
    CLOSURE_STATUSES.APPROVED,
    CLOSURE_STATUSES.PENDING_SETTLEMENT,
    CLOSURE_STATUSES.REJECTED,
    CLOSURE_STATUSES.CANCELLED,
  ],
  [CLOSURE_STATUSES.APPROVED]: [
    CLOSURE_STATUSES.COMPLETED,
    CLOSURE_STATUSES.PENDING_SETTLEMENT,
    CLOSURE_STATUSES.REJECTED,
    CLOSURE_STATUSES.CANCELLED,
  ],
  [CLOSURE_STATUSES.COMPLETED]: [], // Terminal immutable state
  [CLOSURE_STATUSES.REJECTED]: [],  // Terminal
  [CLOSURE_STATUSES.CANCELLED]: [], // Terminal
};

export const closureChecklistConfig = {
  requiredFields: [
    'lockerEmptied',
    'lockerInspected',
    'customerKeyReturned',
    'documentsReturned',
    'physicalAccessRevoked',
  ],
};
